"""Add git_events table

Revision ID: 3ab987fef6f8
Revises: 06a0c4fa04d3
Create Date: 2025-11-10 10:53:02.701834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ab987fef6f8'
down_revision: Union[str, Sequence[str], None] = '06a0c4fa04d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('git_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_name', sa.String(), nullable=True),
    sa.Column('commit_hash', sa.String(), nullable=True),
    sa.Column('commit_message', sa.String(), nullable=True),
    sa.Column('event_time', sa.DateTime(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('time_entry_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['time_entry_id'], ['time_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_git_events_branch_name'), 'git_events', ['branch_name'], unique=False)
    op.create_index(op.f('ix_git_events_commit_hash'), 'git_events', ['commit_hash'], unique=False)
    op.create_index(op.f('ix_git_events_id'), 'git_events', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_git_events_id'), table_name='git_events')
    op.drop_index(op.f('ix_git_events_commit_hash'), table_name='git_events')
    op.drop_index(op.f('ix_git_events_branch_name'), table_name='git_events')
    op.drop_table('git_events')
    # ### end Alembic commands ###
